# Generated by Django 3.2.5 on 2022-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=220)),
                ('predicted_code', models.CharField(max_length=4)),
                ('predicted_number', models.CharField(max_length=10)),
                ('predicted_emirate', models.CharField(max_length=10)),
                ('predicted_color', models.CharField(max_length=10)),
                ('gt_code', models.CharField(max_length=4)),
                ('gt_number', models.CharField(max_length=10)),
                ('gt_emirate', models.CharField(max_length=10)),
                ('gt_color', models.CharField(max_length=10)),
                ('csv_file', models.CharField(max_length=100)),
            ],
        ),
    ]
