# Generated by Django 3.2.5 on 2022-02-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0002_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='salesman',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
